language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "stable"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libicu-dev
env:
- CXX=g++-5
before_script: g++ -v
