sudo: false
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "stable"
compilers:
  - gcc-4.8
  - gcc-4.9
  - gcc-5.3
  - gcc-6.1
  - clang-3.4
  - clang-3.5
  - clang-3.6
  - clang-3.7
addons:
  apt:
    packages:
    - libicu-dev
